spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  flyway:
    table: schema_version
    locations: classpath:db/migration/postgres
  datasource:
    url: ${VEILARBREGISTRERINGDB_URL}
    username: ${VEILARBREGISTRERINGDB_USERNAME}
    password: ${VEILARBREGISTRERINGDB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

server:
  servlet:
    context-path: /veilarbregistrering
  shutdown: graceful

springdoc:
  packages-to-scan: no.nav.fo.veilarbregistrering
  paths-to-match: /api/**

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /internal
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
