apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: veilarbregistrering-unleash
  namespace: paw
  labels:
    "team": "paw"
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: paw
  secretName: veilarbregistrering-unleash-api-token
  environment: production
